### ISSUE TITLE
SecurityException on Android 10 devices

### ISSUE THREAD

**Issue by zhaobozhen** [zhanghai/AppIconLoader#3]
Exception message:

> java.lang.SecurityException: You need INTERACT_ACROSS_USERS or MANAGE_USERS permission to: check isManagedProfile

Stack traces:

> android.os.Parcel.createException Parcel.java:2071
android.os.Parcel.readException Parcel.java:2039
android.os.Parcel.readException Parcel.java:1987
android.os.IUserManager$Stub$Proxy.isManagedProfile IUserManager.java:2427
android.os.UserManager.isManagedProfile UserManager.java:1592
android.app.ApplicationPackageManager.isManagedProfile ApplicationPackageManager.java:2880
android.app.ApplicationPackageManager.getUserBadgedIcon ApplicationPackageManager.java:1459
me.zhanghai.android.appiconloader.iconloaderlib.BaseIconFactory.createBadgedIconBitmap BaseIconFactory.java
me.zhanghai.android.appiconloader.AppIconLoader$IconFactory.createBadgedIconBitmap AppIconLoader.java
me.zhanghai.android.appiconloader.AppIconLoader.loadIcon AppIconLoader.java
me.zhanghai.android.appiconloader.AppIconLoader.loadIcon AppIconLoader.java
com.absinthe.libchecker.recyclerview.adapter.AppAdapter$convert$$inlined$apply$lambda$1.invokeSuspend AppAdapter.java
kotlin.coroutines.jvm.internal.BaseContinuationImpl.c BaseContinuationImpl.java:6
kotlinx.coroutines.DispatchedTask.run DispatchedTask.java
kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely CoroutineScheduler.java
kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask CoroutineScheduler.java
kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker CoroutineScheduler.java
kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run CoroutineScheduler.java

Devices:
* Redmi Note 5 Pro(Android 10)
* CDY-AN90(Android 10)

**Comment by zhanghai** [comment]
The user comes from `UserHandle.getUserHandleForUid(applicationInfo.uid)` in `AppIconLoader.loadIcon()`. How did you get an `ApplicationInfo` for a package in a user that you don't have access to?

The call to `PackageManager.getUserBadgedIcon()` which threw the `SecurityException` is inside AOSP iconloaderlib, so I would prefer leaving it as is.

A simple workaround would be overwriting the `applicationInfo.uid` to make its user ID part be a user that you have access to, before passing it to AppIconLoader. But whether this is logically valid depends on your use case.

**Comment by zhaobozhen** [comment]
感谢指教。我已经修改了我的用例，如果我仍有疑问，未来会重开此问题再向您请教。😊
